services:
  
  mathhunt.api:
    image: mathhunt.api:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
  
  mathhunt.cache:
    image: redis:latest
    restart: always
    ports:
      - '6379:6379'

  mathhunt.postgresDb:
    container_name: postgresDb
    image: postgres:latest
    environment:
      POSTGRES_DB: "skillDb"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "123"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres-data:
  