services:
  mathhunt:
    image: mathhunt:latest
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8080:8081"

  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_DB: "skillDb"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "123"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres-data: 
